pipeline {
  agent any

  environment {
    APP_NAME = "auth-microservice"
    PORT = "5050"
  }

  stages {
    stage('Preparation') {
      steps {
        sh '''
          set +e
          docker stop ${APP_NAME} 2>/dev/null
          docker rm ${APP_NAME} 2>/dev/null
          set -e
        '''
      }
    }

    stage('Build') {
      steps {
        sh 'docker build -t ${APP_NAME}:latest .'
      }
    }

    stage('Run') {
      steps {
        sh 'docker run -d -p ${PORT}:${PORT} --name ${APP_NAME} ${APP_NAME}:latest'
      }
    }

    stage('Test') {
      steps {
        sh '''
          set -e
          # wacht héél kort tot Flask luistert
          for i in 1 2 3 4 5; do
            curl -s http://127.0.0.1:${PORT}/health && break
            sleep 1
          done

          # Health check
          curl -s http://127.0.0.1:${PORT}/health | grep '"status":"ok"'

          # Signup + login flow
          curl -s -X POST -F "username=alice" -F "password=MyS3cret!" http://127.0.0.1:${PORT}/signup | grep "signup success"
          curl -s -X POST -F "username=alice" -F "password=MyS3cret!" http://127.0.0.1:${PORT}/login  | grep "login success"
        '''
      }
    }
  }

  post {
    always {
      sh '''
        set +e
        docker logs ${APP_NAME} --tail 50
        docker stop ${APP_NAME}
        docker rm ${APP_NAME}
        set -e
      '''
    }
  }
}
